version: "3.3"

services:
  webserver:
    build: ./webserver
    ports:
      - "8000:8000"
    volumes:
      - "./webserver/static:/server/static"
      - "./webserver/templates:/server/templates"
    depends_on:
      - postgres
  postgres:
    image: "postgres:14"
    environment:
      - PGUSER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=database
